// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TravelAPI.Models;

namespace TravelAPI.Migrations
{
    [DbContext(typeof(TravelAPIContext))]
    [Migration("20211025165902_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("TravelAPI.Models.Destination", b =>
                {
                    b.Property<int>("DestinationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("Review")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500) CHARACTER SET utf8mb4");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20) CHARACTER SET utf8mb4");

                    b.HasKey("DestinationId");

                    b.ToTable("Destinations");

                    b.HasData(
                        new
                        {
                            DestinationId = 1,
                            City = "Barcelona",
                            Country = "Spain",
                            Rating = 4,
                            Review = "Let me go",
                            Username = "Matilda"
                        },
                        new
                        {
                            DestinationId = 2,
                            City = "San Diego",
                            Country = "Japan",
                            Rating = 5,
                            Review = "It's great",
                            Username = "Rexie"
                        },
                        new
                        {
                            DestinationId = 3,
                            City = "Tokyo",
                            Country = "Japan",
                            Rating = 5,
                            Review = "Totemo iidesu",
                            Username = "Matilda"
                        },
                        new
                        {
                            DestinationId = 4,
                            City = "Buenos Aires",
                            Country = "Argentina",
                            Rating = 4,
                            Review = "Hyperinflation made me a millionaire",
                            Username = "Pip"
                        },
                        new
                        {
                            DestinationId = 5,
                            City = "Krakow",
                            Country = "Poland",
                            Rating = 3,
                            Review = "Best accordian music ever",
                            Username = "Pip"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
